services:
  postgres:
    image: 'postgres:latest'
    container_name: nuxt-boilerplate_postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: 'no'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
