x-defaults: &defaults
  restart: no
  networks:
    - nuxt-boilerplate

x-healthcheck-defaults: &healthcheck-defaults
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 30s

services:
  postgres:
    <<: *defaults
    image: postgres:18-alpine
    container_name: nuxt-boilerplate_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      <<: *healthcheck-defaults
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']

  adminer:
    <<: *defaults
    image: adminer:latest
    container_name: nuxt-boilerplate_adminer
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
    ports:
      - ${ADMINER_PORT:-8080}:8080

networks:
  nuxt-boilerplate:
    driver: bridge
    name: nuxt-boilerplate_network

volumes:
  postgres_data:
  redis_data:
  minio_data:
